ROI         = {'Cz'};             % Channel to be analyzed
event_type  = 'F';           % event around which to cut trials
trial_lim_s = [-0.2 1];       % window in SEC for cutting trials
%plt_lim     = [-0.2 1];         % window for plotting these results
demean_yn   = 'yes';
bsln_lim    = [-0.2 -0.05];    % windowt in SEC for baseline correction
stat_lim    = [0 0.6];            % window in SEC for stats
n_boots     = 1000;             % Repetitions for non-parametric stats
lp_yn       = 'yes';
lp_freq     = 20;
hp_yn       = 'yes';
hp_freq     = 0.5;
hp_filtord  = 4;

cfg_stat = [];
cfg_stat.latency          = stat_lim;
cfg_stat.channel          = 'all';
cfg_stat.parameter        = 'trial';
cfg_stat.method           = 'montecarlo';
cfg_stat.statistic        = 'ft_statfun_indepsamplesT';
cfg_stat.correctm         = 'cluster';
cfg_stat.clusteralpha     = 0.05;   %threshold for a single comparison (time point) to be included in the clust
cfg_stat.clusterstatistic = 'maxsum';
cfg_stat.clustertail      = 0;
cfg_stat.tail             = 0; %two sided
cfg_stat.correcttail      = 'alpha'; %correct the .alpha for two-tailed test (/2)
cfg_stat.alpha            = 0.05;
cfg_stat.numrandomization = n_boots;
cfg_stat.neighbours       = [];%neighbors;
% cfg_stat.minnbchan        = 0;
cfg_stat.ivar             = 1;  %row of design matrix containing independent variable
% cfg_stat.uvar             = 2;  %row containing dependent variable, not needed for indepsamp

cfg_tfr.method = 'wavelet'
cfg_tfr.output = 'pow';
cfg_tfr.taper = 'hanning';
cfg_tfr.foi = [2:30]; 
cfg_tfr.width = 2; %default
cfg_tfr.toi  = 0:0.004:2.8; 
